name: Go Toolchain Tests
on:
  pull_request:
  push:
    branches:
      - cf
      - '*/cf-**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Run tests
        run: ./all.bash
        working-directory: src